### PR TITLE
Use "Constituent List" endpoint to get active members and geocode them

### PR DESCRIPTION
**Pull request by alexsoble**
# Notes 

Great find from @Noleli on this endpoint! We tested it against the production database and saw that it successfully returned a list of active members, as defined by constituents who have the "Member" constituent code.

Note that I'm using a big ole query instead of paginating in order to avoid writing code to handle pagination at this point. If/when membership grows a lot we'll need to improve/update this code.

### CODE REVIEW

**Comment by alexsoble** [comment]
@Noleli @emilyfeder This could be why the process ran twice: https://stackoverflow.com/questions/25504149/why-does-running-the-flask-dev-server-run-itself-twice

**Comment by emilyfeder** [comment]
Did using the no-reload option work? If I have time I can take a look as well. Otherwise the code itself looks good; just make sure tests pass before merging.

**Comment by alexsoble** [comment]
I didn't test the `--no-reload` code yet. I told myself that I wanted to go back and manually delete the duplicate Coordinates fields from the 10 test users who got duplicates because of the bugs first. 

But maybe that's [yak shaving!](https://seths.blog/2005/03/dont_shave_that/). The 10 test users with duplicates aren't hurting anyone or messing anything up, and I having two Coordinates custom fields instead of one shouldn't affect the queries that the front-end will call to gather up everyone's location data. So perhaps I should just move on and test the `--no-reload` code.

**Comment by alexsoble** [comment]
OK, back to this project after midterm elections! 

I went in and deleted the duplicate "Coordinates" fields in the 10 test users for data cleanliness and personal satisfaction. About 4/10 had already been cleaned up.

Now to test the `--no-reload` code!

**Comment by alexsoble** [comment]
Re-ran the coordinates-updating code for the first 10 members in the list again. No Coordinates fields expected to change, because these constituents were previously geocoded. 

Results looked like this:

```
Geocoding for constituent_id: X...
Updating RENEXT custom field for X...
Coordinates haven't changed for this constituent...
```
... except for one case when the script caught a duplicate that I missed! 

```
Updating RENEXT custom field for Y...
Error: more than one Coordinates custom field on constituent: Y
```

**Comment by alexsoble** [comment]
Updating the limit to 20 constituents and running the geocode script again.

**Comment by alexsoble** [comment]
☝️ the test above was successful! Pulled out three constituents from the ten "new" constituents. All had Coordinates custom fields that matched the location of their addresses on file; none had duplicates. 

Interestingly, two were businesses or foundations. I thought that all "constituent" records were individuals but that's not the case.

**Comment by alexsoble** [comment]
Setting `limit=3000` in the query and seeing if we can geocode all active members...

**Comment by alexsoble** [comment]
@Noleli Job still running! Console output looking 👌!

**Comment by alexsoble** [comment]
@Noleli Still running...

**Comment by alexsoble** [comment]
Still running...

Pulled one constituent ID out of the console output and checked their profile. They are an active member but have no home address listed. Their Coordinates custom field value was set to `"None,None"` by the script.

**Comment by alexsoble** [comment]
Done! Ran to the end, reached the `return("Done")` line, every geocoded constituent I checked had a correct Coordinates value or was some kind of edge case (not an individual, no address listed).

**Comment by Noleli** [comment]
Amazing! Great work Alex and Emily. Now it’s time to step up work on the front end, eh?

**Comment by alexsoble** [comment]
@Noleli 😆

**Comment by alexsoble** [comment]
Looking at what @emilyfeder said above: "the code itself looks good; just make sure tests pass before merging."

Now that tests are green (and data has been updated in production by this script) I'll merge this one in.

**Pull request merged**
