### PR TITLE
When user clicks on a Ward, show info for constituents in that Ward

### PR DESCRIPTION
**Pull request by alexsoble**
~ Looking really good after great styles and code patterns from @Noleli merged in with PR #26! ~

### CODE REVIEW

**Comment by alexsoble** [comment]
@emilyfeder @Noleli Pulling down this branch and letting me know what you see would be helpful!

**Comment by emilyfeder** [comment]
The ui looks so good!! Loved the ease of interaction and animations when clicking on the map.
One thing (unrelated to this particular PR) is that right now it's taking a minute for fetch_geocoded_constituents to respond. That's with my home wifi which downloads at 70mb/s.

**Comment by alexsoble** [comment]
@emilyfeder 🙌 :ship

**Comment by alexsoble** [comment]
@emilyfeder I saw the same kind of load speed. Adding a "loading state" graphic of some sort (spinner, progress bar, something creative) could be a good improvement.

**Pull request merged**
